### ISSUE TITLE
Have problem 1 while installing

### ISSUE THREAD

**Issue by luckydevilru** [Jhnbrn90/socialite-passport#3]
**I want to add socailite-passport but have errors:** 

`
$ composer require jhnbrn90/socialite-passport
Using version ^1.0 for jhnbrn90/socialite-passport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Conclusion: don't install jhnbrn90/socialite-passport 1.0.3
    - Conclusion: don't install jhnbrn90/socialite-passport v1.0.2
    - Conclusion: don't install jhnbrn90/socialite-passport v1.0.1
    - Conclusion: remove laravel/framework v7.13.0
    - Installation request for jhnbrn90/socialite-passport ^1.0 -> satisfiable by jhnbrn90/socialite-passport[1.0.3, v1.0.0, v1.0.1, v1.0.2].
    - Conclusion: don't install laravel/framework v7.13.0
    - jhnbrn90/socialite-passport v1.0.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.10|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.11|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.12|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.13|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.14|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.15|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.16|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.17|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.18|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.2|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.3|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.4|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.5|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.6|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.7|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.8|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.18.9|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.13.0
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.13.0
    - Installation request for laravel/framework (locked at v7.13.0, required as ^7.0) -> satisfiable by laravel/framework[v7.13.0].

**Installation failed, reverting ./composer.json to its original content.**`

**Comment by Jhnbrn90** [comment]
Dear @Stalin99 

I've added support for Laravel 7 now in a new release version.
If you would require the package again now, it should install correctly.

**Comment by luckydevilru** [comment]
@Jhnbrn90 thanks! 

Well done!
